version: '3'

dotenv: ['.env']

tasks:
  setup:
    cmds:
      - task: install_k3d
      - task: create_cluster
      - task: verify_cluster
      - task: switch_context
      - task: install_argocd
      - task: install_strimzi_kafka
      - task: finalizing_cluster
      - task: install_prometheus
      - task: print_setup_complete

  install_k3d:
    cmds:
      - wget -q -O - https://raw.githubusercontent.com/k3d-io/k3d/main/install.sh | bash
    desc: Install k3d

  create_cluster:
    cmds:
      - unset KUBECONFIG; k3d cluster create -i rancher/k3s:v1.30.0-rc1-k3s1 -s 3 -p "443:443@loadbalancer" -p "80:80@loadbalancer" ch10-crossplane
    desc: Create Kubernetes cluster with k3d

  verify_cluster:
    cmds:
      - echo "Verifying k3d cluster status..."
      - until k3d cluster list | grep -q '3/3'; do
          k3d cluster list;
          sleep 3;
        done
      - echo "Cluster is up and running:"
      - k3d cluster list
    desc: Verify k3d cluster is running

  switch_context:
    cmds:
      - kubectl config use-context k3d-ch10-crossplane
    desc: Switch context to k3d-ch10-crossplane

  install_kubectl:
    cmds:
      - curl -LO https://dl.k8s.io/release/v1.33.0/bin/linux/arm64/kubectl
      - install -o root -g root -m 0755 kubectl /usr/local/bin/kubectl
      - chmod +x kubectl
      - mkdir -p ~/.local/bin
      - mv ./kubectl ~/.local/bin/kubectl
      - kubectl version --client --output=yaml

  install_argocd:
    cmds:
      - helm repo add argo https://argoproj.github.io/argo-helm
      - helm install argocd argo/argo-cd --namespace argocd --create-namespace
      - kubectl apply -f ../../Ingress/argocd-ingress.yaml
      - kubectl -n argocd get secret argocd-initial-admin-secret -o jsonpath="{.data.password}" | base64 -d
      - kubectl -n argocd patch deployment argocd-server --type='json' -p='[{"op":"add","path":"/spec/template/spec/containers/0/args/-","value":"--insecure"}]'
      - VERSION=$(curl -L -s https://raw.githubusercontent.com/argoproj/argo-cd/stable/VERSION) ; curl -sSL -o argocd-linux-arm64 https://github.com/argoproj/argo-cd/releases/download/v$VERSION/argocd-linux-arm64 ; sudo install -m 555 argocd-linux-arm64 /usr/local/bin/argocd ; rm argocd-linux-arm64
    desc: Install ArgoCD via Helm

  install_strimzi_kafka:
    cmds:
      - kubectl apply -f ../../applications/argo_apps_manifests/strimzi-kafka.yaml
  
  install_prometheus:
    cmds:
      - helm repo add prometheus-community https://prometheus-community.github.io/helm-charts
      - helm install prometheus prometheus-community/prometheus
      - |
        echo "Waiting for Prometheus pod to be ready..."
        while [[ $(kubectl get pods -n default -l app.kubernetes.io/component=server -o jsonpath="{.items[0].status.phase}") != "Running" ]]; do
          sleep 2
        done
        POD_NAME=$(kubectl get pods -n default -l app.kubernetes.io/component=server -o jsonpath="{.items[0].metadata.name}")
        kubectl port-forward -n default $POD_NAME 9090:9090 &
    desc: Install Prometheus via Helm

  finalizing_cluster:
    cmds:
      - k3d node create ch10-crossplane-worker   --cluster ch10-crossplane   --replicas 3   --role agent   --image rancher/k3s:v1.30.0-rc1-k3s1
      - sed -i 's/0.0.0.0/127.0.0.1/g' ~/.kube/config  
 
  print_setup_complete:
    cmds:
      - echo "Local Packt Management Kubernetes server is set up. Author - Bogomil Kovachev."
    desc: Print setup completion message
