---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: nginx
  namespace: flux-system
spec:
  interval: 1m0s
  path: ./ch2/apps/overlays/ch2/nginx
  prune: true
  sourceRef:
    kind: GitRepository
    name: gitops
  targetNamespace: default
