kube-prometheus-stack:
  alertmanager:
    enabled: true

  grafana:
    enabled: true
    adminPassword: prom-operator
    service:
      type: ClusterIP
    ingress:
      enabled: false

  prometheus:
    prometheusSpec:
      retention: 7d
      resources:
        limits:
          cpu: 200m
          memory: 512Mi
        requests:
          cpu: 100m
          memory: 256Mi
      serviceMonitorSelectorNilUsesHelmValues: false
      podMonitorSelectorNilUsesHelmValues: false

  kubeStateMetrics:
    enabled: true

  prometheus-node-exporter:
    enabled: true
