---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: python-demo
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: python-demo
  replicas: 2
  template:
    metadata:
      labels:
        app.kubernetes.io/name: python-demo
    spec:
      containers:
      - name: python-demo
        image: registry.localhost:5000/python-demo:1.0.0
        ports:
        - containerPort: 5000
          name: http
