apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: jenkins
  namespace: default
spec:
  interval: 5m
  chart:
    spec:
      chart: jenkins
      version: 5.3.1
      sourceRef:
        kind: HelmRepository
        name: jenkins
        namespace: default
      interval: 1m
  values:
    controller:
      additionalPlugins:
        - pipeline-stage-view:2.34
        - pipeline-graph-view:304.va_f2a_16b_e4964
      JCasC:
        configScripts:
          welcome-message: |
            jenkins:
              systemMessage: Welcome to our [Packt] GitOps Simplified.
